[package]
name = "ras-x86-repr"
version = "0.1.0"
authors = ["Gabriela Alexandra Moldovan <gabi_250@live.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
csv = "1.1.6"
quote = "1.0.18"
proc-macro2 = "1.0.37"
syn = "1.0.92"
