[package]
name = "ras"
version = "0.1.0"
authors = ["Gabriela Alexandra Moldovan <gabi_250@live.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
target-lexicon = "0.11.1"

[build-dependencies]
csv = "1.1.5"
quote = "1.0.8"
proc-macro2 = "1.0.24"
