[package]
name = "ras-x86"
version = "0.1.0"
authors = ["Gabriela Alexandra Moldovan <gabi_250@live.com>"]
edition = "2018"

[dependencies]
ras-x86-repr = { path = "../ras-x86-repr" }
lazy_static = "1.4.0"
target-lexicon = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.2"
faerie = "0.16.0"

[build-dependencies]
ras-x86-repr = { path = "../ras-x86-repr" }
csv = "1.1.5"
ras-x86-csv = { path = "../ras-x86-csv" }
bincode = "1.3.2"
